network:
  num_blocks: 3
  num_seg_class: 1
  rescale_factor: 0.1
  input_size:
    - 128
    - 128
    - 128
  hidden_dim: 128
  coord_emb_dim: 192
prediction:
  model_weights_filename: pretrained/task2_wh.hdf5
  image:
    image_folder: examples/images
    image_folder_attr: _test
    modality:
      - ct
  mesh:
    mesh_dat_filemame: templates/train_dat/wh_noerode/05_31_2023_10_53_24_bbw.dat
    mesh_tmplt_filename: templates/train_dat/wh_noerode/05_31_2023_10_53_24_template.vtp
    swap_bc_coordinates: null
    num_mesh: 7
  output_folder: output/task2
  mode: test
train:
    batch_size: 1
    lr: 0.001
    num_epoch: 300
    pre_train: pretrained/task2_wh.hdf5
    pre_train_unet: null
    mesh_dat_filemame: examples/task2/05_31_2023_10_53_24_bbw.dat
    data:
        train_img_folder:
            - /path/to/to/original/image/dir
            - /path/to/to/random/cropped/image/dir
            - /path/to/to/augmented/image/dir
        val_img_folder: 
            - /path/to/to/original/image/dir
        file_pattern: '*.tfrecords'
        train_sub_folder_attr: ['', '', '']
        val_sub_folder_attr: ['']
        train_sub_folder_weights: [1., 0.5, 1]
        val_sub_folder_weights: [1.] 
        mesh_ids: [0, 1, 2, 3, 4, 5, 6] 
        modality: 
            - ct
            - mr
        seed: 41
    loss:
        seg_wt: 100
        geom_wt: [0.3, 0.46, 25.]
        mesh_wt: [0.5, 0.5, 0.5]
        chamfer_ratio: 1.
        if_mask: True
        if_cap: True
        turn_off_l2: False
    output_folder: output/task2/test


