network:
  num_blocks: 3
  num_seg_class: 1
  rescale_factor: 0.1
  input_size:
    - 128
    - 128
    - 128
  hidden_dim: 128
  coord_emb_dim: 192
prediction:
  model_weights_filename: pretrained/task2_wh.hdf5
  image:
    image_folder: examples/images
    image_folder_attr: _test
    modality:
      - ct
  mesh:
    mesh_dat_filemame: templates/train_dat/lv_myo_noerode/04_04_2025_14_41_33_bbw.dat
    mesh_tmplt_filename: templates/train_dat/lv_myo_noerode/04_04_2025_14_41_33_template.vtp
    swap_bc_coordinates: null
    num_mesh: 7
  output_folder: output/task2
  mode: test
train:
    batch_size: 1
    lr: 0.001
    num_epoch: 300
    pre_train: null
    pre_train_unet: null
    mesh_dat_filemame: templates/train_dat/lv_myo_noerode/04_04_2025_15_15_27_bbw.dat
    data:
        train_img_folder:
            - /home/cm21/mnt/rds/DeformNet/MMWHS/tfrecords_augmented/
        val_img_folder: 
            - /home/cm21/mnt/rds/DeformNet/MMWHS/tfrecords/
        file_pattern: '*.tfrecords'
        train_sub_folder_attr: ['']
        val_sub_folder_attr: ['']
        train_sub_folder_weights: [1.]
        val_sub_folder_weights: [1.] 
        mesh_ids: [0]
        modality: 
            - ct
        seed: 41
    loss:
        seg_wt: 100
        geom_wt: [0.3, 0.46, 25.]
        mesh_wt: [0.5, 0.5, 0.5]
        chamfer_ratio: 1.
        if_mask: True
        if_cap: False
        turn_off_l2: False
    output_folder: output/task2/test


